[grid]
# hidden_dim = [128, 256, 512]
hidden_dim = [512]
# active_tasks = [["personality","ah"], ["emotion", "ah"], ["emotion", "personality"]]
# alpha_sup = [1.25]
# alpha_ssl = [1.0]
# w_lr_sup = [0.01]
# w_lr_ssl = [0.005]
# lambda_ssl = [0.3]

[defaults]
hidden_dim = 512
